language: node_js

# Use container-based infrastructure
sudo: false

node_js:
  - "node"
  - "6"
  - "8"

script:
  - yarn ci

after_script:
  - codeclimate-test-reporter < coverage/lcov.info

addons:
    code_climate:
        repo_token: d75c6fd7b05635b6687d7709f7f620042747281a0d356148fce5678ddf401772